name: Backport merged pull request
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest

    if: >
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.issue.pull_request.merged &&
        github.event.comment.user.id != 97796249 &&
        startsWith(github.event.comment.body, '/backport')
      )
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          target_branches=$(echo ${{github.event.comment.body}} | cut -c 11-)
          echo "::set-output name=target_branches::$target_branches"
      - name: Create backport pull requests
        uses: korthout/backport-action@v3
        with:
          branch_name: backport/${target_branch}/${{ github.event.pull_request.head.ref }}
          target_branches: ${{ steps.vars.outputs.target_branches }}
          pull_description: |
            (* This is a backport of #${pull_number} to `${target_branch}`. *)

            ---

            ${pull_description}

